---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ['forwarded_port', {guest: 3000, host: 3000, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  always_update_cookbooks: true

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-6.6
    attributes:
      orchestrator:
        configure_database: true
        package:
          version: 2.1.5-1
          url: 'https://github.com/kplimack/orchestrator-rpm/raw/master/orchestrator-2.1.5-1.x86_64.rpm'
          checksum: 392a2d6b3d5cea85053dfad3b6c2dceae838674d56f267046c854e4d1ceee2a3
  - name: centos-7.2
  - name: debian-8.9

suites:
  - name: default
    run_list:
    - recipe[orchestrator::default]
